version: 0.2

# https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-cd-pipeline.html
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - env
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 216989126682.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=$(aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME --output text --query "repositories[0].repositoryUri")
      - echo test $REPOSITORY_URI
      - IMAGE_TAG=$(echo release-$CODEBUILD_RESOLVED_SOURCE_VERSION)
  build:
    commands:
      - echo Build started on `date`
      - REPOSITORY_URI=$(aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME --output text --query "repositories[0].repositoryUri")
      - echo Building the Docker image $IMAGE_REPO_NAME:$IMAGE_TAG...
      - docker build -t app_repo .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"example","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
